export const barterItems = [
  // Smartphones
  {
    id: 1,
    title: 'Samsung Galaxy S21',
    category: 'smartphone',
    price: 35000,
    condition: 'Good',
    description: 'Samsung Galaxy S21, 2 years old, in good working condition with minor scratches.',
    imageBg: 'bg-blue-400',
    icon: '📱',
    owner: {
      name: 'Ahmed Khan',
      rating: 4.7,
      swaps: 12,
    },
    location: 'Gulshan, Dhaka',
    swapValue: 32000,
  },
  {
    id: 2,
    title: 'iPhone 13 Pro',
    category: 'smartphone',
    price: 65000,
    condition: 'Excellent',
    description: 'iPhone 13 Pro, 1 year old, perfect condition with original box and accessories.',
    imageBg: 'bg-gray-400',
    icon: '📱',
    owner: {
      name: 'Fatima Rahman',
      rating: 4.9,
      swaps: 8,
    },
    location: 'Banani, Dhaka',
    swapValue: 60000,
  },
  {
    id: 3,
    title: 'OnePlus 9',
    category: 'smartphone',
    price: 25000,
    condition: 'Good',
    description: 'OnePlus 9, 1.5 years old, good condition with original charger.',
    imageBg: 'bg-red-400',
    icon: '📱',
    owner: {
      name: 'Rahim Ali',
      rating: 4.5,
      swaps: 5,
    },
    location: 'Dhanmondi, Dhaka',
    swapValue: 22000,
  },
  {
    id: 4,
    title: 'Xiaomi Mi 11',
    category: 'smartphone',
    price: 18000,
    condition: 'Very Good',
    description: 'Xiaomi Mi 11, 1 year old, excellent condition with all accessories.',
    imageBg: 'bg-orange-400',
    icon: '📱',
    owner: {
      name: 'Sadia Khan',
      rating: 4.6,
      swaps: 7,
    },
    location: 'Mirpur, Dhaka',
    swapValue: 15000,
  },

  // Cars
  {
    id: 5,
    title: 'Toyota Corolla 2019',
    category: 'car',
    price: 850000,
    condition: 'Very Good',
    description: 'Toyota Corolla 2019, automatic, low mileage, well maintained.',
    imageBg: 'bg-red-400',
    icon: '🚗',
    owner: {
      name: 'Mohammad Ali',
      rating: 4.5,
      swaps: 15,
    },
    location: 'Dhanmondi, Dhaka',
    swapValue: 800000,
  },
  {
    id: 6,
    title: 'Honda City 2020',
    category: 'car',
    price: 750000,
    condition: 'Excellent',
    description: 'Honda City 2020, automatic, single owner, full service history.',
    imageBg: 'bg-gray-400',
    icon: '🚗',
    owner: {
      name: 'Karim Hossain',
      rating: 4.8,
      swaps: 10,
    },
    location: 'Uttara, Dhaka',
    swapValue: 700000,
  },
  {
    id: 7,
    title: 'Suzuki Swift 2018',
    category: 'car',
    price: 550000,
    condition: 'Good',
    description: 'Suzuki Swift 2018, manual, economical, perfect for city driving.',
    imageBg: 'bg-blue-400',
    icon: '🚗',
    owner: {
      name: 'Nadia Rahman',
      rating: 4.4,
      swaps: 8,
    },
    location: 'Mohammadpur, Dhaka',
    swapValue: 500000,
  },

  // Laptops
  {
    id: 8,
    title: 'MacBook Pro 2021',
    category: 'laptop',
    price: 85000,
    condition: 'Excellent',
    description: 'MacBook Pro 2021, M1 chip, 16GB RAM, 512GB SSD, perfect condition.',
    imageBg: 'bg-gray-400',
    icon: '💻',
    owner: {
      name: 'Tahsin Ahmed',
      rating: 4.9,
      swaps: 6,
    },
    location: 'Gulshan, Dhaka',
    swapValue: 80000,
  },
  {
    id: 9,
    title: 'Dell XPS 13',
    category: 'laptop',
    price: 65000,
    condition: 'Very Good',
    description: 'Dell XPS 13, i7 processor, 16GB RAM, 512GB SSD, 2 years old.',
    imageBg: 'bg-blue-400',
    icon: '💻',
    owner: {
      name: 'Fahim Khan',
      rating: 4.7,
      swaps: 9,
    },
    location: 'Banani, Dhaka',
    swapValue: 60000,
  },
  {
    id: 10,
    title: 'Lenovo ThinkPad',
    category: 'laptop',
    price: 35000,
    condition: 'Good',
    description: 'Lenovo ThinkPad, i5 processor, 8GB RAM, 256GB SSD, business laptop.',
    imageBg: 'bg-black',
    icon: '💻',
    owner: {
      name: 'Sabbir Rahman',
      rating: 4.5,
      swaps: 12,
    },
    location: 'Dhanmondi, Dhaka',
    swapValue: 32000,
  },

  // Furniture
  {
    id: 11,
    title: 'Modern Sofa Set',
    category: 'furniture',
    price: 45000,
    condition: 'Excellent',
    description: '3-piece modern sofa set, barely used, premium quality fabric.',
    imageBg: 'bg-amber-400',
    icon: '🛋️',
    owner: {
      name: 'Nusrat Jahan',
      rating: 4.8,
      swaps: 5,
    },
    location: 'Gulshan, Dhaka',
    swapValue: 42000,
  },
  {
    id: 12,
    title: 'Wooden Dining Table',
    category: 'furniture',
    price: 25000,
    condition: 'Very Good',
    description: '6-seater wooden dining table with chairs, solid wood construction.',
    imageBg: 'bg-amber-600',
    icon: '🪑',
    owner: {
      name: 'Rashid Khan',
      rating: 4.6,
      swaps: 7,
    },
    location: 'Banani, Dhaka',
    swapValue: 22000,
  },
  {
    id: 13,
    title: 'Office Desk',
    category: 'furniture',
    price: 8000,
    condition: 'Good',
    description: 'Modern office desk with drawers, perfect for home office.',
    imageBg: 'bg-amber-500',
    icon: '🪑',
    owner: {
      name: 'Tahmina Begum',
      rating: 4.4,
      swaps: 4,
    },
    location: 'Mirpur, Dhaka',
    swapValue: 7000,
  },

  // Books
  {
    id: 14,
    title: 'Complete Book Collection',
    category: 'books',
    price: 4500,
    condition: 'Very Good',
    description: 'Collection of 20 best-selling novels, all in excellent condition.',
    imageBg: 'bg-purple-400',
    icon: '📚',
    owner: {
      name: 'Zahid Hasan',
      rating: 4.7,
      swaps: 15,
    },
    location: 'Dhanmondi, Dhaka',
    swapValue: 4000,
  },
  {
    id: 15,
    title: 'Academic Books Set',
    category: 'books',
    price: 3000,
    condition: 'Good',
    description: 'Set of engineering textbooks, some highlighting, overall good condition.',
    imageBg: 'bg-purple-500',
    icon: '📚',
    owner: {
      name: 'Sadia Islam',
      rating: 4.5,
      swaps: 8,
    },
    location: 'Uttara, Dhaka',
    swapValue: 2500,
  },

  // Electronics
  {
    id: 16,
    title: 'Sony PlayStation 5',
    category: 'electronics',
    price: 45000,
    condition: 'Excellent',
    description: 'PS5 with 2 controllers and 3 games, barely used.',
    imageBg: 'bg-blue-500',
    icon: '🎮',
    owner: {
      name: 'Rafiq Islam',
      rating: 4.8,
      swaps: 6,
    },
    location: 'Gulshan, Dhaka',
    swapValue: 42000,
  },
  {
    id: 17,
    title: 'Samsung 55" Smart TV',
    category: 'electronics',
    price: 65000,
    condition: 'Very Good',
    description: 'Samsung 55" 4K Smart TV, 2 years old, perfect working condition.',
    imageBg: 'bg-blue-600',
    icon: '📺',
    owner: {
      name: 'Nasir Uddin',
      rating: 4.6,
      swaps: 10,
    },
    location: 'Banani, Dhaka',
    swapValue: 60000,
  },

  // Dress Items
  {
    id: 18,
    title: 'Designer Evening Gown',
    category: 'dress',
    price: 15000,
    condition: 'Excellent',
    description: 'Brand new designer evening gown, never worn, perfect for special occasions.',
    imageBg: 'bg-pink-400',
    icon: '👗',
    owner: {
      name: 'Nadia Rahman',
      rating: 4.8,
      swaps: 6,
    },
    location: 'Gulshan, Dhaka',
    swapValue: 13000,
  },
  {
    id: 19,
    title: 'Traditional Saree Collection',
    category: 'dress',
    price: 12000,
    condition: 'Very Good',
    description: 'Collection of 3 designer sarees, perfect condition, premium quality.',
    imageBg: 'bg-purple-400',
    icon: '👗',
    owner: {
      name: 'Fatima Begum',
      rating: 4.7,
      swaps: 8,
    },
    location: 'Banani, Dhaka',
    swapValue: 10000,
  },

  // Tablet Items
  {
    id: 20,
    title: 'iPad Pro 2022',
    category: 'tablet',
    price: 65000,
    condition: 'Excellent',
    description: 'iPad Pro 2022, 12.9-inch, 256GB, with Apple Pencil and Magic Keyboard.',
    imageBg: 'bg-gray-400',
    icon: '📱',
    owner: {
      name: 'Rahim Khan',
      rating: 4.9,
      swaps: 5,
    },
    location: 'Dhanmondi, Dhaka',
    swapValue: 60000,
  },
  {
    id: 21,
    title: 'Samsung Galaxy Tab S8',
    category: 'tablet',
    price: 45000,
    condition: 'Very Good',
    description: 'Samsung Galaxy Tab S8, 11-inch, 128GB, with S Pen, perfect for work and entertainment.',
    imageBg: 'bg-blue-400',
    icon: '📱',
    owner: {
      name: 'Sadia Islam',
      rating: 4.6,
      swaps: 7,
    },
    location: 'Uttara, Dhaka',
    swapValue: 40000,
  },

  // Motorcycle Items
  {
    id: 22,
    title: 'Yamaha R15 V4',
    category: 'motorcycle',
    price: 250000,
    condition: 'Excellent',
    description: 'Yamaha R15 V4, 2022 model, single owner, low mileage, perfect condition.',
    imageBg: 'bg-red-400',
    icon: '🏍️',
    owner: {
      name: 'Karim Hossain',
      rating: 4.8,
      swaps: 3,
    },
    location: 'Mirpur, Dhaka',
    swapValue: 230000,
  },
  {
    id: 23,
    title: 'Honda CBR 250R',
    category: 'motorcycle',
    price: 180000,
    condition: 'Very Good',
    description: 'Honda CBR 250R, 2021 model, well maintained, all service records available.',
    imageBg: 'bg-red-500',
    icon: '🏍️',
    owner: {
      name: 'Tahsin Ahmed',
      rating: 4.7,
      swaps: 4,
    },
    location: 'Gulshan, Dhaka',
    swapValue: 160000,
  },

  // House Items
  {
    id: 24,
    title: 'Modern Apartment',
    category: 'house',
    price: 450000,
    condition: 'Excellent',
    description: '3BHK apartment in prime location, fully furnished, modern amenities.',
    imageBg: 'bg-amber-400',
    icon: '🏠',
    owner: {
      name: 'Mohammad Ali',
      rating: 4.9,
      swaps: 2,
    },
    location: 'Banani, Dhaka',
    swapValue: 420000,
  },
  {
    id: 25,
    title: 'Luxury Villa',
    category: 'house',
    price: 850000,
    condition: 'Excellent',
    description: '5BHK luxury villa with garden, swimming pool, and modern security system.',
    imageBg: 'bg-amber-500',
    icon: '🏠',
    owner: {
      name: 'Nasir Uddin',
      rating: 4.8,
      swaps: 1,
    },
    location: 'Gulshan, Dhaka',
    swapValue: 800000,
  },

  // Kitchen Items
  {
    id: 26,
    title: 'Modern Kitchen Set',
    category: 'kitchen',
    price: 45000,
    condition: 'Excellent',
    description: 'Complete kitchen set including refrigerator, oven, microwave, and utensils.',
    imageBg: 'bg-orange-400',
    icon: '🍳',
    owner: {
      name: 'Nusrat Jahan',
      rating: 4.7,
      swaps: 5,
    },
    location: 'Dhanmondi, Dhaka',
    swapValue: 42000,
  },
  {
    id: 27,
    title: 'Premium Cookware Set',
    category: 'kitchen',
    price: 15000,
    condition: 'Very Good',
    description: 'High-quality cookware set with 10 pieces, non-stick, perfect condition.',
    imageBg: 'bg-orange-500',
    icon: '🍳',
    owner: {
      name: 'Rashida Begum',
      rating: 4.6,
      swaps: 6,
    },
    location: 'Uttara, Dhaka',
    swapValue: 13000,
  },

  // Tools Items
  {
    id: 28,
    title: 'Professional Tool Kit',
    category: 'tools',
    price: 12000,
    condition: 'Excellent',
    description: 'Complete professional tool kit with 50+ pieces, perfect for DIY projects.',
    imageBg: 'bg-gray-600',
    icon: '🔧',
    owner: {
      name: 'Rafiq Islam',
      rating: 4.8,
      swaps: 8,
    },
    location: 'Mirpur, Dhaka',
    swapValue: 10000,
  },
  {
    id: 29,
    title: 'Power Tools Set',
    category: 'tools',
    price: 25000,
    condition: 'Very Good',
    description: 'Set of power tools including drill, saw, and sander, barely used.',
    imageBg: 'bg-gray-700',
    icon: '🔧',
    owner: {
      name: 'Sabbir Rahman',
      rating: 4.7,
      swaps: 5,
    },
    location: 'Mohammadpur, Dhaka',
    swapValue: 22000,
  }
]; 